Algorithm development2
pnnl/ANIMATE pull request #23
Opened 2022-06-24 22:19 UTC by yunjoonjung-PNNL

I added 3 more verification items (1. Automatic Shutdown 2. Heat Pump Supplemental Heat Lockout, 3. Heat Rejection Fan Variable Flow Controls). 

I'd appreciate it if you could review this PR. I will make adjustments based on the feedback. Thank you!

2022-06-27 21:31 UTC, leijerry888 requested changes

2022-06-27 23:10 UTC, yunjoonjung-PNNL commented on src/library.py
> +        copied_df = self.df.copy(
1. deep copy was fixed.
2. The reason why I renamed the ```index``` to ```Date``` was that I had to do grouping in line 521 and in order to do grouping I needed the timestamp column (not as index).

2022-06-28 02:09 UTC, yunjoonjung-PNNL commented on src/library.py
> +        if reg.coef_[0] >= 1.4:
I will get this updated after we discussed this with Jeremy.

2022-06-30 23:41 UTC, leijerry888 approved these changes
code changes to be reviewed together with algorithm_development

2022-06-30 23:44 UTC, merged